after_training: null
agent: tonic.torch.agents.DDPG()
before_training: null
checkpoint: last
environment: tonic.environments.Bullet('AntBulletEnv-v0')
environment_name: null
header: import tonic.torch
name: ddpg-ant-vanilla-new
parallel: 1
path: null
seed: 0
sequential: 1
test_environment: null
trainer: null
